baseURL = "https://benkoerbel.com/"
languageCode = "en-us"
title = "Ben Koerbel"
theme = "aerial"

[params]
  name = "Ben Koerbel"
  about = "This is my webpage."
  copyright = "2017"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = ""
  favicon = "favicon.ico"